# Auto-generated fallback emoji text for each custom emoji id.
SERVICE_EMOJI_ALTS = {
    '3ds max': '📱',
    'ableton live': '📱',
    'adobe after effects': '📱',
    'adobe animate': '📱',
    'adobe audition': '📱',
    'adobe illustrator': '📱',
    'adobe indesign': '📱',
    'adobe photoshop': '📱',
    'adobe premiere pro': '📱',
    'airbnb': '📱',
    'amazon': '📱',
    'app store': '📱',
    'apple': '📱',
    'apple music': '📱',
    'apple podcasts': '📱',
    'artstation': '📱',
    'badoo': '📱',
    'bandlab': '📱',
    'behance': '📱',
    'bigo live': '📱',
    'bitcoin': '📱',
    'blender': '📱',
    'botim': '📱',
    'bumble': '📱',
    'c': '📱',
    'c plus plus': '📱',
    'capcut': '📱',
    'chatgpt': '📱',
    'cinema 4d': '📱',
    'copilot': '📱',
    'cpp': '📱',
    'cubase': '📱',
    'daraz': '📱',
    'davinci resolve': '📱',
    'deviantart': '📱',
    'discord': '📱',
    'disney': '📱',
    'dribbble': '📱',
    'dropbox': '📱',
    'dune ai': '📱',
    'ethereum': '📱',
    'evernote': '📱',
    'facebook': '📱',
    'figma': '📱',
    'firefox': '📱',
    'flickr': '📱',
    'foodpanda': '📱',
    'foursquare': '📱',
    'freepik': '📱',
    'github': '📱',
    'gitlab': '📱',
    'goodgame studios': '📱',
    'google chrome': '📱',
    'google drive': '📱',
    'google earth': '📱',
    'google maps': '📱',
    'google play': '📱',
    'google play store': '📱',
    'gpt': '📱',
    'hbo': '📱',
    'hbo max': '📱',
    'hinge': '📱',
    'hulu': '📱',
    'imdb': '📱',
    'imo': '📱',
    'instagram': '📱',
    'java': '📱',
    'javascript': '📱',
    'js': '📱',
    'kakaotalk': '📱',
    'kanopy': '📱',
    'kickstarter': '📱',
    'kwai': '📱',
    'letterboxd': '📱',
    'likee': '📱',
    'line': '📱',
    'linkedin': '📱',
    'mastercard': '📱',
    'max': '📱',
    'max hbo': '📱',
    'maya': '📱',
    'medium': '📱',
    'mega': '📱',
    'messenger': '📱',
    'meta': '📱',
    'microsoft copilot': '📱',
    'microsoft edge': '📱',
    'microsoft store': '📱',
    'midjourney': '📱',
    'netflix': '📱',
    'nordvpn': '📱',
    'notion': '📱',
    'odnoklassniki': '📱',
    'odnoklassniki ok': '📱',
    'ok': '📱',
    'onlyfans': '📱',
    'openai': '📱',
    'opera': '📱',
    'paramount': '📱',
    'patreon': '📱',
    'paypal': '📱',
    'pinterest': '📱',
    'play store': '📱',
    'playstation': '📱',
    'plex': '📱',
    'procreate': '📱',
    'pure': '📱',
    'python': '📱',
    'qq': '📱',
    'quora': '📱',
    'reddit': '📱',
    'rotten tomatoes': '📱',
    'rust': '📱',
    'safari': '📱',
    'shazam': '📱',
    'signal': '📱',
    'sketch': '📱',
    'skrill': '📱',
    'skype': '📱',
    'slack': '📱',
    'snapchat': '📱',
    'soundcloud': '📱',
    'spline': '📱',
    'spotify': '📱',
    'stability ai': '📱',
    'steam': '📱',
    'sublime text': '📱',
    'suno': '📱',
    'ted': '📱',
    'telegram': '📱',
    'tether usdt': '📱',
    'threads': '📱',
    'tiktok': '📱',
    'tinder': '📱',
    'toncoin': '📱',
    'triller': '📱',
    'tumblr': '📱',
    'twitch': '📱',
    'twitter': '📱',
    'twitter x': '📱',
    'unity': '📱',
    'unreal engine': '📱',
    'upwork': '📱',
    'utorrent': '📱',
    'viber': '📱',
    'vimeo': '📱',
    'visa': '📱',
    'visual studio code': '📱',
    'vk': '📱',
    'vscode': '📱',
    'wechat': '📱',
    'weibo': '📱',
    'whatsapp': '📱',
    'wikipedia': '📱',
    'wolframalpha': '📱',
    'x': '📱',
    'x twitter': '📱',
    'xbox': '📱',
    'xiaohongshu': '📱',
    'yandex maps': '📱',
    'youtube': '📱',
    'youtube music': '📱',
    'youtube shorts': '📱',
    'zalo': '📱',
    'zbrush': '📱',
    'zbrush alternate': '📱',
    'zoom': '📱',
}

COUNTRY_EMOJI_ALTS = {
    'abkhazia': '🚩',
    'afghanistan': '🇦🇫',
    'aland islands': '🇦🇽',
    'albania': '🇦🇱',
    'algeria': '🇩🇿',
    'america': '🇺🇸',
    'american samoa': '🇦🇸',
    'andorra': '🇦🇩',
    'angola': '🇦🇴',
    'anguilla': '🇦🇮',
    'antigua and barbuda': '🇦🇬',
    'argentina': '🇦🇷',
    'armenia': '🇦🇲',
    'aruba': '🇦🇼',
    'australia': '🇦🇺',
    'austria': '🇦🇹',
    'azerbaijan': '🇦🇿',
    'bahamas': '🇧🇸',
    'bahrain': '🇧🇭',
    'bangladesh': '🇧🇩',
    'barbados': '🇧🇧',
    'belarus': '🇧🇾',
    'belgium': '🇧🇪',
    'belize': '🇧🇿',
    'benin': '🇧🇯',
    'bhutan': '🇧🇹',
    'bolivia': '🇧🇴',
    'botswana': '🇧🇼',
    'brazil': '🇧🇷',
    'britain': '🇬🇧',
    'brunei': '🇧🇳',
    'bulgaria': '🇧🇬',
    'burkina faso': '🇧🇫',
    'burundi': '🇧🇮',
    'cambodia': '🇰🇭',
    'cameroon': '🇨🇲',
    'canada': '🇨🇦',
    'cape verde': '🇨🇻',
    'central african republic': '🇨🇫',
    'chad': '🇹🇩',
    'chile': '🇨🇱',
    'china': '🇨🇳',
    'colombia': '🇨🇴',
    'comoros': '🇰🇲',
    'congo': '🇨🇬',
    'cook islands': '🇨🇰',
    'costa rica': '🇨🇷',
    'cote d ivoire': '🇨🇮',
    'croatia': '🇭🇷',
    'cuba': '🇨🇺',
    'cyprus': '🇨🇾',
    'czech': '🇨🇿',
    'czech republic': '🇨🇿',
    'denmark': '🇩🇰',
    'djibouti': '🇩🇯',
    'dominica': '🇩🇲',
    'dominican republic': '🇩🇴',
    'ecuador': '🇪🇨',
    'egypt': '🇪🇬',
    'el salvador': '🇸🇻',
    'emirates': '🇦🇪',
    'england': '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f',
    'equatorial guinea': '🇬🇶',
    'eritrea': '🇪🇷',
    'estonia': '🇪🇪',
    'ethiopia': '🇪🇹',
    'european union': '🇪🇺',
    'finland': '🇫🇮',
    'france': '🇫🇷',
    'gabon': '🇬🇦',
    'gambia': '🇬🇲',
    'georgia': '🇬🇪',
    'germany': '🇩🇪',
    'ghana': '🇬🇭',
    'gibraltar': '🇬🇮',
    'great britain': '🇬🇧',
    'greece': '🇬🇷',
    'greenland': '🇬🇱',
    'guatemala': '🇬🇹',
    'guinea': '🇬🇳',
    'guinea bissau': '🇬🇼',
    'guyana': '🇬🇾',
    'haiti': '🇭🇹',
    'honduras': '🇭🇳',
    'hong kong': '🇭🇰',
    'hong kong sar': '🇭🇰',
    'hungary': '🇭🇺',
    'iceland': '🇮🇸',
    'india': '🇮🇳',
    'iran': '🇮🇷',
    'iraq': '🇮🇶',
    'ireland': '🇮🇪',
    'isle of man': '🇮🇲',
    'israel': '🇮🇱',
    'italy': '🇮🇹',
    'ivory coast': '🇨🇮',
    'jamaica': '🇯🇲',
    'japan': '🇯🇵',
    'jersey': '🇯🇪',
    'jordan': '🇯🇴',
    'kazakhstan': '🇰🇿',
    'kenya': '🇰🇪',
    'kiribati': '🇰🇮',
    'korea': '🇰🇷',
    'ksa': '🇸🇦',
    'kuwait': '🇰🇼',
    'kyrgyzstan': '🇰🇬',
    'laos': '🇱🇦',
    'latvia': '🇱🇻',
    'lebanon': '🇱🇧',
    'lesotho': '🇱🇸',
    'liberia': '🇱🇷',
    'libya': '🇱🇾',
    'liechtenstein': '🇱🇮',
    'lithuania': '🇱🇹',
    'luxembourg': '🇱🇺',
    'madagascar': '🇲🇬',
    'malawi': '🇲🇼',
    'malaysia': '🇲🇾',
    'maldives': '🇲🇻',
    'mali': '🇲🇱',
    'malta': '🇲🇹',
    'marshall islands': '🇲🇭',
    'mauritania': '🇲🇷',
    'mauritius': '🇲🇺',
    'mexico': '🇲🇽',
    'micronesia': '🇫🇲',
    'moldova': '🇲🇩',
    'monaco': '🇲🇨',
    'mongolia': '🇲🇳',
    'morocco': '🇲🇦',
    'mozambique': '🇲🇿',
    'myanmar': '🇲🇲',
    'namibia': '🇳🇦',
    'nauru': '🇳🇷',
    'nepal': '🇳🇵',
    'netherlands': '🇵🇬',
    'new zealand': '🇳🇿',
    'nicaragua': '🇳🇮',
    'niger': '🇳🇪',
    'nigeria': '🇳🇬',
    'niue': '🇳🇺',
    'north korea': '🇰🇵',
    'north macedonia': '🇲🇰',
    'norway': '🇳🇴',
    'oman': '🇴🇲',
    'pakistan': '🇵🇰',
    'palestine': '🇵🇸',
    'palestine state': '🇵🇸',
    'panama': '🇵🇦',
    'papua new guinea': '🇵🇬',
    'paraguay': '🇵🇾',
    'peru': '🇵🇪',
    'philippines': '🇵🇭',
    'poland': '🇵🇱',
    'portugal': '🇵🇹',
    'puerto rico': '🇵🇷',
    'qatar': '🇶🇦',
    'republic of the congo': '🇨🇬',
    'romania': '🇷🇴',
    'russia': '🇷🇺',
    'russia federation': '🇷🇺',
    'rwanda': '🇷🇼',
    'san marino': '🇸🇲',
    'sao tome and principe': '🇸🇹',
    'saudi': '🇸🇦',
    'saudi arabia': '🇸🇦',
    'scotland': '🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f',
    'senegal': '🇸🇳',
    'serbia': '🇷🇸',
    'seychelles': '🇸🇨',
    'sierra leone': '🇸🇱',
    'singapore': '🇸🇬',
    'slovakia': '🇸🇰',
    'slovenia': '🇸🇮',
    'solomon islands': '🇸🇧',
    'somalia': '🇸🇴',
    'south africa': '🇿🇦',
    'south korea': '🇰🇷',
    'spain': '🇪🇸',
    'sri lanka': '🇱🇰',
    'sudan': '🇸🇩',
    'suriname': '🇸🇷',
    'swaziland': '🇸🇿',
    'sweden': '🇸🇪',
    'switzerland': '🇨🇭',
    'syria': '🇸🇾',
    'taiwan': '🇹🇼',
    'tajikistan': '🇹🇯',
    'tanzania': '🇹🇿',
    'thailand': '🇹🇭',
    'togo': '🇹🇬',
    'tonga': '🇹🇴',
    'trinidad and tobago': '🇹🇹',
    'tunisia': '🇹🇳',
    'turkey': '🇹🇷',
    'turkiye': '🇹🇷',
    'turkmenistan': '🇹🇲',
    'turks and caicos islands': '🇹🇨',
    'uae': '🇦🇪',
    'uganda': '🇺🇬',
    'uk': '🇬🇧',
    'ukraine': '🇺🇦',
    'united arab emirates': '🇦🇪',
    'united kingdom': '🇬🇧',
    'united states': '🇺🇸',
    'united states of america': '🇺🇸',
    'uruguay': '🇺🇾',
    'us': '🇺🇸',
    'usa': '🇺🇸',
    'uzbekistan': '🇺🇿',
    'vanuatu': '🇻🇺',
    'venezuela': '🇻🇪',
    'viet nam': '🇻🇳',
    'vietnam': '🇻🇳',
    'virgin islands': '🇻🇮',
    'wales': '🏴\U000e0067\U000e0062\U000e0077\U000e006c\U000e0073\U000e007f',
    'yemen': '🇾🇪',
    'zambia': '🇿🇲',
    'zimbabwe': '🇿🇼',
}

ACTION_EMOJI_EXACT_ALTS = {
    'admin': '🎉',
    'back': '🔙',
    'broadcast': '📣',
    'close': '🔙',
    'country': '🌐',
    'custom': '✅',
    'delete': '🖥',
    'fastest': '💥',
    'get_number': '💬',
    'lock': '❌',
    'manage': '🖥',
    'message_otp': '💬',
    'open_bot': '💬',
    'otp': '💬',
    'phone': '👀',
    'refresh': '❌',
    'rocket': '☄️',
    'select_option': '☄️',
    'service': '✅',
    'stats': '📈',
    'stock': '📈',
    'success': '✅',
    'upload': '🖥',
    'user_mode': '🔙',
    'verify': '✅',
    'voice_otp': '🎙',
    'waiting_otp': '👀',
    'warning': '❌',
    'welcome': '🔥',
}

